project_id = "xunlqdiappgyokhknvoc"

[functions.generate-sensor-data]
verify_jwt = false

[functions.generate-air-quality-report]
verify_jwt = false

[functions.check-prolonged-alerts]
verify_jwt = false

[functions.generate-monthly-report]
verify_jwt = false

[functions.sensor-data-webhook]
verify_jwt = false

[functions.device-health-monitor]
verify_jwt = false