// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xunlqdiappgyokhknvoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bmxxZGlhcHBneW9raGtudm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzUwMTQsImV4cCI6MjA3NDQxMTAxNH0.yFpwOFX-as13l6ZXUOaVSa1Kr2CWWzAa9LZzXHB2JAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});